# Generated by Django 3.0 on 2021-08-05 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(choices=[('HK', 'Hong Kong'), ('IT', 'Italy'), ('ES', 'Spain'), ('DK', 'Denmark'), ('FR', 'France')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.TextField(max_length=50)),
                ('ingredients', models.TextField()),
                ('weight', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('season', models.TextField(choices=[('SEASON_WINTER', 'Winter'), ('SEASON_SPRING', 'Spring'), ('SEASON_SUMMER', 'Summer'), ('SEASON_AUTUMN', 'Autumn')])),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=64)),
                ('season_dish', models.CharField(choices=[('SEASON_WINTER', 'Winter'), ('SEASON_SPRING', 'Spring'), ('SEASON_SUMMER', 'Summer'), ('SEASON_AUTUMN', 'Autumn')], max_length=64)),
                ('list_of_dishes', models.ManyToManyField(to='tutorial.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('position', models.TextField(choices=[('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('COOK', 'Cook'), ('CLEANER', 'Cleaner'), ('SOMMELIER', 'Sommelier')])),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VEA', 'VEA'), ('ANTICHI_SAPORI', 'Antichi Sapori'), ('GANBARA', 'Ganbara'), ('NOMA', 'Noma'), ('SATURNE', 'Saturne')], max_length=50)),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Staff')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Country')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Menu')),
            ],
        ),
    ]
