# Generated by Django 3.0 on 2021-08-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
