# Generated by Django 3.0 on 2021-08-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_auto_20210811_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
